### ISSUE TITLE
Dataset link not found

### ISSUE THREAD

**Issue by JavaAiNiU** [donikv/Cube2#1]
Hi，
    Click the dataset link to prompt: This page cannot be accessed. Has this link changed?

**Comment by donikv** [comment]
Hi, yes the link has changed, we're moving the dataset to another service. I will update the link soon and let you know when it's done.

**Comment by JavaAiNiU** [comment]
> Hi, yes the link has changed, we're moving the dataset to another service. I will update the link soon and let you know when it's done.

Ok，Thanks

**Comment by donikv** [comment]
I have added a new link, so I'm closing this issue, the dataset should be accessible now
